version: '3'

volumes:
  pg_data:
  static:
  static_backend:
  media_volume:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: mokriiiii/foodgram_backend
    env_file: .env
    volumes:
        - static_backend:/app/collected_static/
        - media_volume:/app/media/
    depends_on:
        - db
  frontend:
    image: mokriiiii/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: nginx:1.19.3
    ports:
      - '8000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - static_backend:/var/html/static/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_volume:/media/
    depends_on:
      - frontend
    restart: always